{% set name = "case" %}
{% set version = "1.5.3" %}
{% set sha256 = "48432b01d91913451c3512c5b90e31b0f348f1074b166a3431085eb70d784fb1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - nose >=1.3.7
    - unittest2 >=0.5.1  # [py26]
    - mock >=2.0.0

test:
  imports:
    - case

about:
  home: http://github.com/celery/case
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python unittest Utilities'

  doc_url: http://case.readthedocs.io/
  dev_url: https://github.com/celery/case

extra:
  recipe-maintainers:
    - sodre
