travis:
  secure:
    BINSTAR_TOKEN: SNUkOFW4yFVw0CT52YxXubkmmJYcEzoxI7d3lBJBfiPRwGGz0nTguTerWNNiId+vmmj6M4f35S6tSQrVWCRCYXz9p1KptvQFMMUe/UYB+vIEjWdmTFQp111DyekznhZa/oCnV7zwCBNPvI87wuYSCApd5AJ9hujPBqA2lwW5NiXEAUsP2QKYc8FjfpGI4dig9rwUc6mXM06LLLeaBp4E1TMumiLsJNDd+gUdfaj94NjUMQNtZhkcd7rYyUSyHyLBIxUriCR8NBGCdHXSkOOtfYYftWKxoTXCsgyh39Q0/kOYLO7Jb+4444OIz1DzI8dNF8MR+5K39lnCmRbNguWIZMgioqtTP7E9wna2841WPQ46js9tDO6P6zFqHxTCaOfFjmungYXoiCYUICFrkpaj12PCAytk/+cBCNmfyuINVbnMDUsEdZRf2qHfC2VK5Ne/reHBxFj2pTlQNdg7eAmF//JIEMvc4rg1sYqHqSgLJ37NLPMJXy+IYxSYnVkeiIGBW4TMdAJV/HfW9IZM8vHkR6pfyTnEVUcv48Q5WZpkAhFhl21BGlaVir0hhWhs5ti97aYEbiu7CRmYp39laDFYJi+B1+Pl6DysDflInV6xwUCNj7iDWxyTKZwReov6KHjmF9JvA7pPKqX6FoKlcRYTFgihkb1JfVRShoB/r74SM7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
